# Generated by Django 3.1.7 on 2021-05-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
