# Generated by Django 3.1.7 on 2021-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0003_employee_employer_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
